steps:
    
    - name: 'ggcr.io/cloud-builders/git'
      args: ['pull', 'https://github.com/ppongsak/k8s-centos-phpfm-nginx.git', 'develop']
    # - name: 'gcr.io/cloud-builders/docker'
    #   args: ['pull', 'gcr.io/$PROJECT_ID/k8s-centos-phpfm-nginx']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/k8s-centos-phpfm-nginx', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/k8s-centos-phpfm-nginx:latest']
    - name: 'gcr.io/cloud-builders/kubectl'
      args:
          - 'set'
          - 'image'
          # k8s name
          - 'deployment/php-nginx'
          # container name
          - 'centos-phpfpm-nginx=gcr.io/$PROJECT_ID/k8s-centos-phpfm-nginx:latest'
      env:
          - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-b'
          - 'CLOUDSDK_CONTAINER_CLUSTER=rebate-cluster-dev'
