#step1
steps:
    - name: 'gcr.io/rebatemango-dev/github-ppongsak-k8s-centos-phpfm-nginx'
      args: ['build', '-t', 'gcr.io/rebatemango-dev/$REPO_NAME:1.0', '.']
    - name: 'gcr.io/rebatemango-dev/github-ppongsak-k8s-centos-phpfm-nginx'
      args: ['push', 'gcr.io/rebatemango-dev/$REPO_NAME:1.0']
# images: ['gcr.io/rebatemango-dev/$REPO_NAME:1.0']
