#step1
steps:
    - name: 'gcr.io/cloud-builders/docker'
      args:
          ['build', '-t', 'gcr.io/rebatemango-dev/k8s-centos-phpfm-nginx', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/rebatemango-dev/k8s-centos-phpfm-nginx']
    - name: 'gcr.io/cloud-builders/kubectl'
      args:
          - 'set'
          - 'image'
          - 'deployment/my-deployment'
          - 'my-container=gcr.io/rebatemango-dev/k8s-centos-phpfm-nginx'
