#step1
steps:
    - name: 'gcr.io/cloud-builders/docker'
      args:
          ['build', '-t', 'gcr.io/rebatemango-dev/k8s-centos-phpfm-nginx', '.']
images: ['gcr.io/rebatemango-dev/k8s-centos-phpfm-nginx']
